version: '3'
services:
  bot:
    container_name: eksicodeBot
    build: ./
    volumes:
      - ./:/var/bot
    env_file:
     - .env
    networks:
      - eksicode_nw

volumes:
  bot:

networks:
  eksicode_nw:
